on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
 
      - name: Install GraalVM
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz
          if [ $? -ne 0 ]; then
            echo "Falha ao baixar o GraalVM. Verifique a versão."
            exit 1
          fi
          sudo tar -xzf graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz -C /opt
          echo "export PATH=/opt/graalvm-community-jdk-21.0.2_linux-x64_bin/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc
          native-image --version || { echo "native-image não está disponível. Verifique a instalação do GraalVM."; exit 1; }

      - name: Build project
        run: |
          cd app/pom.xml  # Altere para o diretório que contém o pom.xml
          mvn clean package -Pnative
 
      - name: List files in target directory
        run: |
          cd app/target  # Altere para o diretório target correto
          ls -l
 
      - name: Create ZIP for Lambda
        run: |
          cd app/target  # Altere para o diretório correto
          zip meu-lambda.zip lambda-graalvm-0.0.1
 
      - name: Upload Native Executable
        uses: actions/upload-artifact@v3
        with:
          name: meu-lambda-executavel
          path: app/target/aws-lambda-java-starter-example  # Altere para o caminho correto
