name: Build Native Lambda
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
 
      - name: Install GraalVM
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/v${{ github.event.repository.package_version }}/graalvm-ce-java21-${{ github.event.repository.package_version }}-linux-amd64.tar.gz
          sudo tar -xzf graalvm-ce-java21-${{ github.event.repository.package_version }}-linux-amd64.tar.gz -C /opt
          echo "export PATH=/opt/graalvm-ce-java21-${{ github.event.repository.package_version }}/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc
          gu install native-image
 
      - name: Build project
        run: mvn clean package
 
      - name: List files in target directory
        run: ls -l target
 
      - name: Create ZIP for Lambda
        run: |
          cd target
          zip meu-lambda.zip aws-lambda-java-starter-example-0.0.1
 
      - name: Upload Native Executable
        uses: actions/upload-artifact@v3
        with:
          name: meu-lambda-executavel
          path: target/aws-lambda-java-starter-example
