on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Install GraalVM
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz
          if [ $? -ne 0 ]; then
            echo "Falha ao baixar o GraalVM. Verifique a versão."
            exit 1
          fi
          sudo tar -xzf graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz -C /opt
          echo "export PATH=/opt/graalvm-community-jdk-21.0.2_linux-x64_bin/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc
          native-image --version || { echo "native-image não está disponível. Verifique a instalação do GraalVM."; exit 1; }

      - name: Build project
        run: |
          cd app  # Altere para o diretório que contém o pom.xml
          mvn clean package -Pnative -DskipTests -Dgraalvm.native-image.args="--static"

      - name: List target directory after build
        run: ls -l app/target

      - name: Create bootstrap file
        run: |
          echo '#!/bin/sh' > bootstrap
          echo 'exec ./lambda-graalvm' >> bootstrap
          chmod +x bootstrap  # Torna o arquivo bootstrap executável

      - name: Move executables to root
        run: |
          mv app/target/lambda-graalvm ./
          chmod +x ./lambda-graalvm  # Torna o executável disponível

      - name: List root directory
        run: ls -l

      - name: Create ZIP for Lambda
        run: |
          zip meu-lambda.zip bootstrap lambda-graalvm

      - name: Upload Native Executable
        uses: actions/upload-artifact@v3
        with:
          name: meu-lambda-executavel
          path: meu-lambda.zip
